// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NPV.DatabaseCore;

namespace NPV.DatabaseCore.Migrations
{
    [DbContext(typeof(NPVContext))]
    [Migration("20190509140126_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("NPV.Models.Entities.PreviousResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("DiscountRateIncrement");

                    b.Property<decimal>("InitialCost");

                    b.Property<int>("LifeOfProject");

                    b.Property<double>("LowerBoundDiscountRate");

                    b.Property<decimal>("NetPresentValue");

                    b.Property<decimal>("PresentValueOfCashFlows");

                    b.Property<double>("UpperBoundDiscountRate");

                    b.HasKey("Id");

                    b.ToTable("PreviousResults");
                });
#pragma warning restore 612, 618
        }
    }
}
